package com.mycompany.arena202301;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JCheckBox;

/**
 *
 * @author
 */
public class CofiguracionArmas extends javax.swing.JFrame {

    //public Defensa arma;
    
    public CofiguracionArmas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always 
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        deContacto = new java.awt.Checkbox();
        medianoAlcance = new java.awt.Checkbox();
        aereos = new java.awt.Checkbox();
        impacto = new java.awt.Checkbox();
        ataqueMultiple = new java.awt.Checkbox();
        bloques = new java.awt.Checkbox();
        label3 = new java.awt.Label();
        nombre = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        vida = new java.awt.TextField();
        ataque = new java.awt.TextField();
        campos = new java.awt.TextField();
        aparicion = new java.awt.TextField();
        cargar = new java.awt.Button();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        aparicion1 = new java.awt.TextField();
        label15 = new java.awt.Label();
        imagen1 = new java.awt.TextField();
        label17 = new java.awt.Label();
        imagen2 = new java.awt.TextField();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label14 = new java.awt.Label();
        rango = new java.awt.TextField();
        label16 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        label1.setText("Armas");

        label2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label2.setText("Tipo de arma");

        deContacto.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        deContacto.setLabel("De contacto");

        medianoAlcance.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        medianoAlcance.setLabel("Mediano Alcance");

        aereos.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        aereos.setLabel("Aéreos");

        impacto.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        impacto.setLabel("Impacto");

        ataqueMultiple.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        ataqueMultiple.setLabel("Ataque Múltiple");

        bloques.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        bloques.setLabel("Bloques");

        label3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label3.setText("Nombre");

        nombre.setName(""); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label6.setText("Vida");

        label7.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label7.setText("Ataque");

        label8.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label8.setText("Campos");

        label9.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label9.setText("Aparición");

        vida.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        ataque.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataqueActionPerformed(evt);
            }
        });

        aparicion.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        cargar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        cargar.setLabel("Cargar");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        label10.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label10.setText("golpes");

        label11.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label11.setText("golpe por segundo");

        label12.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label12.setText("nivel");

        label13.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label13.setText("Campos");

        aparicion1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        label15.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label15.setText("Imagen 1");

        imagen1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        label17.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label17.setText("Imagen 2");

        imagen2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        label18.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label18.setText("(con excepción de armas");

        label19.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label19.setText("de Contacto y Bloques)");

        label14.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label14.setText("Rango");

        rango.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        label16.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label16.setText("(solo para las armas de");

        label20.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label20.setText("Impacto)");

        label21.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label21.setText("(con excepción de armas");

        label22.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        label22.setText("aéreas)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ataqueMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(medianoAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ataque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aparicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aparicion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(impacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aereos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(label22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(rango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aereos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ataqueMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(impacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medianoAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aparicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        label18.getAccessibleContext().setAccessibleName("x");
        label16.getAccessibleContext().setAccessibleName("(solo para las armas de");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        Defensa defensa = null;
        
        boolean confirmacion = false;
        
        if(deContacto.isShowing() == true){
            if(nombre.getText().isEmpty() || vida.getText().isEmpty() || ataque.getText().isEmpty() 
                || aparicion.getText().isEmpty() || rango.getText().isEmpty() 
                || campos.getText().isEmpty() || imagen1.getText().isEmpty() 
                || imagen2.getText().isEmpty()){
                
                System.out.println("Todos los campos necesarios deben de ser llenados");
            }
            else{
                defensa = new Defensa(nombre.getText(), Integer.parseInt(vida.getText()), 
                    Integer.parseInt(ataque.getText()), Integer.parseInt(aparicion.getText()),
                    Integer.parseInt(rango.getText()), Integer.parseInt(campos.getText()), 
                    imagen1.getText(), imagen2.getText(), "contacto");
                
                confirmacion = true;
            }
        }
        else if(ataqueMultiple.getState() == true){
            if(nombre.getText().isEmpty() || vida.getText().isEmpty() || ataque.getText().isEmpty() 
                || aparicion.getText().isEmpty() || campos.getText().isEmpty() 
                || imagen1.getText().isEmpty() || imagen2.getText().isEmpty()){
                
                System.out.println("Todos los campos necesarios deben de ser llenados");
            }
            else{
                defensa = new Defensa(nombre.getText(), Integer.parseInt(vida.getText()), 
                        Integer.parseInt(ataque.getText()), Integer.parseInt(aparicion.getText()), 
                        Integer.parseInt(campos.getText()), imagen1.getText(), imagen2.getText(), "ataqueMultiple");
                
                confirmacion = true;
            }
        }
        else if(medianoAlcance.getState() == true){
            if(nombre.getText().isEmpty() || vida.getText().isEmpty() || ataque.getText().isEmpty() 
                || aparicion.getText().isEmpty() || campos.getText().isEmpty() 
                || imagen1.getText().isEmpty() || imagen2.getText().isEmpty()){
                
                System.out.println("Todos los campos necesarios deben de ser llenados");
            }
            else{
                defensa = new Defensa(nombre.getText(), Integer.parseInt(vida.getText()), 
                        Integer.parseInt(ataque.getText()), Integer.parseInt(aparicion.getText()), 
                        Integer.parseInt(campos.getText()), imagen1.getText(), imagen2.getText(), "medioAlcance");
                
                confirmacion = true;
            }
        }
        else if(aereos.getState() == true){
            if(nombre.getText().isEmpty() || vida.getText().isEmpty() || ataque.getText().isEmpty() 
                || aparicion.getText().isEmpty() || imagen1.getText().isEmpty() 
                || imagen2.getText().isEmpty()){
                
                System.out.println("Todos los campos necesarios deben de ser llenados");
            }
            else{
                defensa = new Defensa(nombre.getText(), Integer.parseInt(vida.getText()), 
                    Integer.parseInt(ataque.getText()), Integer.parseInt(aparicion.getText()), 
                    imagen1.getText(), imagen2.getText(), "aereos");
                
                confirmacion = true;
            }
        }
        else if(impacto.getState() == true){
            if(nombre.getText().isEmpty() || vida.getText().isEmpty() || ataque.getText().isEmpty() 
                || aparicion.getText().isEmpty() || imagen1.getText().isEmpty()){
                
                System.out.println("Todos los campos necesarios deben de ser llenados");
            }
            else{
                defensa = new Defensa(nombre.getText(), Integer.parseInt(vida.getText()), 
                        Integer.parseInt(ataque.getText()), Integer.parseInt(aparicion.getText()), 
                        imagen1.getText(), "impacto");
                
                confirmacion = true;
            }
        }
        else if(bloques.getState() == true){
            if(nombre.getText().isEmpty() || vida.getText().isEmpty() || aparicion.getText().isEmpty() 
                || imagen1.getText().isEmpty()){
                
                System.out.println("Todos los campos necesarios deben de ser llenados");
            }
            else{
                defensa = new Defensa(nombre.getText(), Integer.parseInt(vida.getText()), 
                        Integer.parseInt(aparicion.getText()), imagen1.getText(), "bloques");
                
                confirmacion = true;
            }
        }
        
        if(confirmacion == true){
            try {
            FileOutputStream fileOut = new FileOutputStream("Defensas.dat", true);
            ObjectOutputStream out = new ObjectOutputStream(fileOut);

            out.writeObject(defensa);

            out.close();
            fileOut.close();

            System.out.println("El objeto se ha escrito en el archivo .dat.");
            } catch (IOException e) {
                e.printStackTrace();
            }

            try {
                // Abre el archivo en modo lectura
                FileInputStream fileInputStream = new FileInputStream("Defensas.dat");
                BufferedInputStream bufferedInputStream = new BufferedInputStream(fileInputStream);

                // Lee y almacena el contenido del archivo en un arreglo de bytes
                ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                byte[] buffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = bufferedInputStream.read(buffer)) != -1) {
                    byteArrayOutputStream.write(buffer, 0, bytesRead);
                }

                // Cierra los flujos de entrada
                bufferedInputStream.close();
                fileInputStream.close();

                // Convierte el contenido a una cadena si es necesario
                String contenido = byteArrayOutputStream.toString("UTF-8");

                // Hacer algo con el contenido, por ejemplo, imprimirlo
                System.out.println("Contenido del archivo:");
                System.out.println(contenido);
            } catch (IOException e) {
                e.printStackTrace();
            }

            Configuracion newFrame = new Configuracion();
            newFrame.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_cargarActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void ataqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ataqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CofiguracionArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CofiguracionArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CofiguracionArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CofiguracionArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CofiguracionArmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox aereos;
    private java.awt.TextField aparicion;
    private java.awt.TextField aparicion1;
    private java.awt.TextField ataque;
    private java.awt.Checkbox ataqueMultiple;
    private java.awt.Checkbox bloques;
    private java.awt.TextField campos;
    private java.awt.Button cargar;
    private java.awt.Checkbox deContacto;
    private java.awt.TextField imagen1;
    private java.awt.TextField imagen2;
    private java.awt.Checkbox impacto;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label3;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Checkbox medianoAlcance;
    private java.awt.TextField nombre;
    private java.awt.TextField rango;
    private java.awt.TextField vida;
    // End of variables declaration//GEN-END:variables
}
